[project]
name = "app-shop-counting-shop-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pyodbc>=5.3.0",
]
